// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241119114911_AddItemsAccountingSettingsAndScannedForCompany")]
    partial class AddItemsAccountingSettingsAndScannedForCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.AccountingSettingsElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountingItem_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("AccountingItem_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountingItem_ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountingItem_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AccountingSoftwareAgenda_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("AccountingSoftwareAgenda_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountingSoftwareAgenda_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Activity_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Activity_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Activity_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CashRegister_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("CashRegister_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CashRegister_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ClassificationVat_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("ClassificationVat_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassificationVat_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassificationVat_ValidFrom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassificationVat_ValidTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("ClassificationVat_isReverseCharge")
                        .HasColumnType("bit");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpenditureCenter_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("ExpenditureCenter_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExpenditureCenter_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GeneralDocumentAgenda_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("GeneralDocumentAgenda_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeneralDocumentAgenda_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumericCode_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("NumericCode_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumericCode_PaymentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumericCode_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Order_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Order_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Order_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Order_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PredefinedNote_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("PredefinedNote_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Project_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Project_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Project_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("AccountingSettings", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PropertyRegistrationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.CustomVatInterface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsTaxExempt")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaxBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("VatSummaries", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentErpId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Municipality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrganizationTaxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationVAT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationVatId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiptUID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScanedForCompany")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TaxBaseBasic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxBaseFree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxBaseReduced")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VatAmountBasic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VatAmountFree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VatAmountReduced")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VatRateBasic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VatRateFree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VatRateReduced")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.ExportItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountingSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountingSettingsId");

                    b.HasIndex("DocumentId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.ItemsAccountingSettingsElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountingItem_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("AccountingItem_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingItem_ResourceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingItem_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AccountingSoftwareAgenda_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("AccountingSoftwareAgenda_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingSoftwareAgenda_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Activity_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Activity_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CashRegister_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("CashRegister_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CashRegister_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassificationVat_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("ClassificationVat_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationVat_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationVat_ValidFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationVat_ValidTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ClassificationVat_isReverseCharge")
                        .HasColumnType("bit");

                    b.Property<int?>("ExpenditureCenter_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("ExpenditureCenter_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenditureCenter_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GeneralDocumentAgenda_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("GeneralDocumentAgenda_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralDocumentAgenda_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("NumericCode_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("NumericCode_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumericCode_PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumericCode_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Order_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PredefinedNote_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("PredefinedNote_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Project_AccountingSoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Project_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project_Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemsAccountingSettings");
                });

            modelBuilder.Entity("DataAccess.Entities.AccountingSettingsElement", b =>
                {
                    b.HasOne("DataAccess.Entities.Document", null)
                        .WithOne("AccountingSettings")
                        .HasForeignKey("DataAccess.Entities.AccountingSettingsElement", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Address", b =>
                {
                    b.HasOne("DataAccess.Entities.Document", null)
                        .WithOne("Address")
                        .HasForeignKey("DataAccess.Entities.Address", "DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.CustomVatInterface", b =>
                {
                    b.HasOne("DataAccess.Entities.Document", null)
                        .WithMany("VatSummary")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.ExportItem", b =>
                {
                    b.HasOne("DataAccess.Entities.ItemsAccountingSettingsElement", "AccountingSettings")
                        .WithMany()
                        .HasForeignKey("AccountingSettingsId");

                    b.HasOne("DataAccess.Entities.Document", null)
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccountingSettings");
                });

            modelBuilder.Entity("DataAccess.Entities.Document", b =>
                {
                    b.Navigation("AccountingSettings");

                    b.Navigation("Address");

                    b.Navigation("Items");

                    b.Navigation("VatSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
